### ISSUE TITLE
test GitHub bot

### ISSUE THREAD

**Issue by usulpro** [UsulPro/myjunkstaff#8]
new issue

**Comment by usulpro** [comment]
@UsulPro I want to answer right from telegram

**Comment by usulpro** [comment]
@UsulPro Yes I did this!

**Comment by usulpro** [comment]
@UsulPro Cool!!! 😀🤣😇😂😉😎🤓🤗🤑😛😡😤😠😱😈☠️👺👹👾🎃🙀😽🤖

**Comment by usulpro** [comment]
@UsulPro

**Comment by usulpro** [comment]
@UsulPro 🌤⛅️🌥🌦🌈☁️🌧⛈🌩🌨☃️⛄️❄️🌬💨🌪🌫🌊💧💦☔️

**Comment by dalikat** [comment]
@UsulPro It's my reply 💬

**Comment by dalikat** [comment]
@dalikat Yes

**Comment by usulpro** [comment]
@dalikat @GitHubBot :)

**Comment by usulpro** [comment]
@UsulPro test translation

**Comment by usulpro** [comment]
let's test some features
